// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: transcribe.proto
#ifndef GRPC_transcribe_2eproto__INCLUDED
#define GRPC_transcribe_2eproto__INCLUDED

#include "transcribe.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace transcribe {

class Transcriber final {
 public:
  static constexpr char const* service_full_name() {
    return "transcribe.Transcriber";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::transcribe::AudioData, ::transcribe::Text>> Trans(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::transcribe::AudioData, ::transcribe::Text>>(TransRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::transcribe::AudioData, ::transcribe::Text>> AsyncTrans(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::transcribe::AudioData, ::transcribe::Text>>(AsyncTransRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::transcribe::AudioData, ::transcribe::Text>> PrepareAsyncTrans(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::transcribe::AudioData, ::transcribe::Text>>(PrepareAsyncTransRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Trans(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::transcribe::AudioData,::transcribe::Text>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderWriterInterface< ::transcribe::AudioData, ::transcribe::Text>* TransRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::transcribe::AudioData, ::transcribe::Text>* AsyncTransRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::transcribe::AudioData, ::transcribe::Text>* PrepareAsyncTransRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::transcribe::AudioData, ::transcribe::Text>> Trans(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::transcribe::AudioData, ::transcribe::Text>>(TransRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::transcribe::AudioData, ::transcribe::Text>> AsyncTrans(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::transcribe::AudioData, ::transcribe::Text>>(AsyncTransRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::transcribe::AudioData, ::transcribe::Text>> PrepareAsyncTrans(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::transcribe::AudioData, ::transcribe::Text>>(PrepareAsyncTransRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Trans(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::transcribe::AudioData,::transcribe::Text>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReaderWriter< ::transcribe::AudioData, ::transcribe::Text>* TransRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::transcribe::AudioData, ::transcribe::Text>* AsyncTransRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::transcribe::AudioData, ::transcribe::Text>* PrepareAsyncTransRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Trans_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Trans(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::transcribe::Text, ::transcribe::AudioData>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_Trans : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Trans() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Trans() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Trans(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::transcribe::Text, ::transcribe::AudioData>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTrans(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::transcribe::Text, ::transcribe::AudioData>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Trans<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Trans : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Trans() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::transcribe::AudioData, ::transcribe::Text>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->Trans(context); }));
    }
    ~WithCallbackMethod_Trans() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Trans(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::transcribe::Text, ::transcribe::AudioData>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::transcribe::AudioData, ::transcribe::Text>* Trans(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_Trans<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Trans : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Trans() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Trans() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Trans(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::transcribe::Text, ::transcribe::AudioData>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Trans : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Trans() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Trans() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Trans(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::transcribe::Text, ::transcribe::AudioData>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTrans(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Trans : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Trans() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->Trans(context); }));
    }
    ~WithRawCallbackMethod_Trans() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Trans(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::transcribe::Text, ::transcribe::AudioData>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* Trans(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace transcribe


#endif  // GRPC_transcribe_2eproto__INCLUDED
