// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: transcribe.proto

#include "transcribe.pb.h"
#include "transcribe.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace transcribe {

static const char* Transcriber_method_names[] = {
  "/transcribe.Transcriber/Trans",
};

std::unique_ptr< Transcriber::Stub> Transcriber::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Transcriber::Stub> stub(new Transcriber::Stub(channel, options));
  return stub;
}

Transcriber::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Trans_(Transcriber_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::transcribe::AudioData, ::transcribe::Text>* Transcriber::Stub::TransRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::transcribe::AudioData, ::transcribe::Text>::Create(channel_.get(), rpcmethod_Trans_, context);
}

void Transcriber::Stub::async::Trans(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::transcribe::AudioData,::transcribe::Text>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::transcribe::AudioData,::transcribe::Text>::Create(stub_->channel_.get(), stub_->rpcmethod_Trans_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::transcribe::AudioData, ::transcribe::Text>* Transcriber::Stub::AsyncTransRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::transcribe::AudioData, ::transcribe::Text>::Create(channel_.get(), cq, rpcmethod_Trans_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::transcribe::AudioData, ::transcribe::Text>* Transcriber::Stub::PrepareAsyncTransRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::transcribe::AudioData, ::transcribe::Text>::Create(channel_.get(), cq, rpcmethod_Trans_, context, false, nullptr);
}

Transcriber::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Transcriber_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< Transcriber::Service, ::transcribe::AudioData, ::transcribe::Text>(
          [](Transcriber::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::transcribe::Text,
             ::transcribe::AudioData>* stream) {
               return service->Trans(ctx, stream);
             }, this)));
}

Transcriber::Service::~Service() {
}

::grpc::Status Transcriber::Service::Trans(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::transcribe::Text, ::transcribe::AudioData>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace transcribe

